language: generic
dist: xenial
sudo: required
script:
- bash test.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GDIpYtIKbiGDw8nc/8otUjVgTcnxbM7jnBAy/ov3V08vSR35Jsc/Gc44kpNV64dFpPsvj2BtHOfJCFKfUZ0EBrKTbMjdzwE7OGxpAYATPLk7sIO2lqq7n8wE+hYezmsf2Vc4o62nJ3lL2bom7gfdIOhSGgdA6YG0HsMaDGWwke6tiSvYR5fkSOiA+/xXFIt3OEOOw3in2E75CImtkrFyLsjL/cN3hUjf7mctjEBQvZxdBPs/p+2/twiLMuQ9D/kL8a5HvNXVmEJbvJEC2k7rZfaCkvsE7GTkkyD5/k0nJBCfDiectF1xDy3lypQQN6mI5MJgWpSkMvA3S/te4Hddvs38HPM0rrP7ABpG424WjZE1MhZmXPZGa9q/dXQwurpVRL5S9MjvSvwZvGDstpwfgThwNITn625nk6uGLYrQ+FLtYIEhKK0qormRaUKPLsergHmwrrhukxrxM+kIFsVSIhGX+sx3YLjDC49gAn7bourWl+dyySwEC4Ji12iddeVcYZA8MelgVMdnRcpmKReBsOTm3NRVAcw4EtFkQMtJMQM77zDCEiFwMWKriVDoqJ/kX9aMxc5Lg4EhJ6nhOXy3LzAaO5Fk22BdmerlE5ZYCEhNSaqgB4DFdaTlXQfXSW95Bx6NL/CsfMMRdWFq782fxnqvYWMGjV2G52iL+/gmwlU=
  file: hello.sh
  on:
    repo: sharabinth/TravisTest
    tags: true
